config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      namespace :properties do
        get 'most_guests', to: 'most_guests#index'
        get 'most_expensive', to: 'most_expensive#index'
        get 'by_state', to: 'by_state#index'
        scope ':property_id' do
          resources :reservations, only: [:create]
        end

        resources :search, only: [:index]
        resources :properties, only: [:index]
      end
      namespace :reservations do
        get '/by_month', to: 'month#index'
        get '/revenue_by_month', to: 'revenue_by_month#index'
        get '/highest_revenue_cities', to: 'cities_revenue#index'
        get '/revenue_by_state', to: 'revenue_by_state#index'
      end
      namespace :users do
        namespace :reservations do
          get '/nights', to: 'nights#index'
          get '/bookings', to: 'bookings#index'
        end
        namespace :properties do
          get '/most_properties', to: 'most_properties#index'
        end
        namespace :money do
          get '/most_spent', to: 'most_spent#index'
          get '/most_revenue', to: 'most_revenue#index'
        end
      end
    end
  end

  get '/sign_up', to: 'signup#index'
  get '/log_in', to: 'login#index'
  get '/dashboard', to: 'dashboard#index'
  delete '/logout', to: 'sessions#destroy'

  devise_for :users,
    :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"},
    :path_names => {
    	:verify_authy => "/verify-token",
    	:enable_authy => "/enable_authy",
    	:verify_authy_installation => "/verify-installation"
      }

  resources :users, only: [:edit, :update]

  namespace :admin do
    get '/dashboard', to: 'dashboard#index'
    resources :properties, only: [:index, :edit, :update]
  end

  resources :users, only: [:edit, :update, :show]

  namespace :reservations do
    scope ':reservation_id' do
      resources :property_reviews, only: [:new, :create]
      resources :user_reviews, only: [:new, :create]
    end
  end

  resources :properties,  only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :property_availabilities, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  resources :reservations, only: [:new, :update]

  namespace :user do
    resources :conversations, only: [:index, :show, :create] do
      resources :messages, only: [:create]
    end
    resources :properties, only: [:index, :show]
  end

  mount ActionCable.server => '/cable'
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::BaseController

  def index
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index
    @user = current_user
  end

end

app/views/dashboard/index.html.erb
<div class="row">
  <div class="col-md-3">
    <div class="panel space-4">
        <div class="media media-photo-block">
          <div class="text-center">
            <% if @user.image_url != nil %>
            <%= image_tag @user.image_url + "?type=large", class: "profile-pic-large" %>
            <% end %>
          </div>
        </div>

        <div class="panel-body">
          <h2 class="text-center">
            <%= @user.first_name %></h2>
          <ul class="list-unstyled text-center">
            <li>
              <%= link_to "View Profile", user_path(@user), class: "btn btn-custom" %>
            </li><br>
            <li>
              <%= link_to "Edit Profile", edit_user_path(@user) %>
            </li>
            <li> REVIEWS
              <!-- <%#= link_to "Reviews", user_reviews_path ...or whatever %> -->
            </li>
          </ul>
        </div>
      </div>
  </div>

    <div class="col-md-9">
      <div class="card col-md-12" id="toggle">
        <div class="card_header">
          <ul class = "nav nav-tabs card-header-tabs">
            <li class="nav-item">
              <a class="nav-link" data-toggle="tab" href="#pending">Pending Reservations</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" data-toggle="tab" href="#confirmed">Confirmed Reservations</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" data-toggle="tab" href="#finished">Past Reservations</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" data-toggle="tab" href="#declined">Declined Reservations</a>
            </li>
          </ul>

          <div class="tab-content">
            <div class="tab-pane" id="pending" role="tabpanel">
              <%= render partial: 'reservations/reservations', locals: {status: 'pending', user: @user} %>
            </div>

            <div class="tab-pane" id="confirmed" role="tabpanel">
              <%= render partial: 'reservations/reservations', locals: {status: 'confirmed', user: @user} %>
            </div>

            <div class="tab-pane" id="finished" role="tabpanel">
              <%= render partial: 'reservations/reservations', locals: {status: 'finished', user: @user} %>
            </div>

            <div class="tab-pane" id="declined" role="tabpanel">
              <%= render partial: 'reservations/reservations', locals: {status: 'declined', user: @user} %>
            </div>
          </div>
        </div>
      </div>
    </div>
</div>