config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      namespace :properties do
        get 'most_guests', to: 'most_guests#index'
        get 'most_expensive', to: 'most_expensive#index'
        get 'by_state', to: 'by_state#index'
        scope ':property_id' do
          resources :reservations, only: [:create]
        end

        resources :search, only: [:index]
        resources :properties, only: [:index]
      end
      namespace :reservations do
        get '/by_month', to: 'month#index'
        get '/revenue_by_month', to: 'revenue_by_month#index'
        get '/highest_revenue_cities', to: 'cities_revenue#index'
        get '/revenue_by_state', to: 'revenue_by_state#index'
      end
      namespace :users do
        namespace :reservations do
          get '/nights', to: 'nights#index'
          get '/bookings', to: 'bookings#index'
        end
        namespace :properties do
          get '/most_properties', to: 'most_properties#index'
        end
        namespace :money do
          get '/most_spent', to: 'most_spent#index'
          get '/most_revenue', to: 'most_revenue#index'
        end
      end
    end
  end

  get '/sign_up', to: 'signup#index'
  get '/log_in', to: 'login#index'
  get '/dashboard', to: 'dashboard#index'
  delete '/logout', to: 'sessions#destroy'

  devise_for :users,
    :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"},
    :path_names => {
    	:verify_authy => "/verify-token",
    	:enable_authy => "/enable_authy",
    	:verify_authy_installation => "/verify-installation"
      }

  resources :users, only: [:edit, :update]

  namespace :admin do
    get '/dashboard', to: 'dashboard#index'
    resources :properties, only: [:index, :edit, :update]
  end

  resources :users, only: [:edit, :update, :show]

  namespace :reservations do
    scope ':reservation_id' do
      resources :property_reviews, only: [:new, :create]
      resources :user_reviews, only: [:new, :create]
    end
  end

  resources :properties,  only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :property_availabilities, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  resources :reservations, only: [:new, :update]

  namespace :user do
    resources :conversations, only: [:index, :show, :create] do
      resources :messages, only: [:create]
    end
    resources :properties, only: [:index, :show]
  end

  mount ActionCable.server => '/cable'
end

app/models/property_availability.rb
class PropertyAvailability < ApplicationRecord
  validates :date, presence: true
  validates_uniqueness_of :date, :scope => :property_id
  belongs_to :property

  scope :available, -> {where(reserved: false)}

  def self.set_availability(first_available_date, last_available_date)
    (first_available_date..last_available_date).map do |date|
      PropertyAvailability.create(date: date)
    end
  end

  def self.set_reserved(property_id, check_in, check_out)
    property = Property.find(property_id)
    availabilities = property.property_availabilities.where(:property_availabilities => { date: check_in..check_out })
    availabilities.map do |avail|
      avail.update(reserved: true)
      avail.save
    end
  end
end

app/controllers/property_availabilities_controller.rb
class  PropertyAvailabilitiesController < ApplicationController

  before_action :set_property

  def index
    @property_availabilities = @property.property_availabilities.available
  end

  def new
    @property_availability = @property.property_availabilities.new()
  end

  def create
    @property_availabilities = @property.property_availabilities.set_availability(params[:first_available_date].to_date, params[:last_available_date].to_date)
    ids=[]
    @property_availabilities.each {|prop| ids << prop.id}
    if ids.include?(nil)
      flash[:danger] = "Sorry! Something went wrong. Please check your dates and try again."
      redirect_to new_property_property_availability_path(@property)
    else
      flash[:success] = "Your available dates have been set."
      redirect_to property_path(@property)
    end
  end

  def edit
    @property_availability = @property.property_availabilities.find(params[:id])
  end

  def update
    if params[:reserved] == "true"
      @property_availability.update(reserved: true)
      if @property_availability.save
        flash[:success] = "Your available dates have been changed."
        redirect_to property_property_availability_path(@property)
      else
        render :index
      end
    else
      render :index
    end
  end

  def destroy
    @property_availability = @property.property_availabilities.find(params[:id])
    @property_availability.destroy
    redirect_to property_property_availabilities_path(@property)
  end

private

  def property_availability_params
    params.permit(:first_available_date, :last_available_date, :property_id)
  end

  def set_property
    @property = Property.find(params[:property_id])
  end

end

app/views/property_availabilities/_form.html.erb
<br>
<%= form_tag(property_property_availabilities_path(@property), :html => {:class => 'form-horizontal'}) do  %>

  <div class="form-group">
    <%= label_tag(:first_available_date) %>

  <%= date_field_tag :first_available_date%>
  </div>

  <div class="form-group">
    <%= label_tag(:last_available_date) %>
    <%= date_field_tag :last_available_date %>
  </div>
  <br>
  <%= submit_tag "Complete", class: 'btn btn-custom' %>
  <% end %>

app/views/property_availabilities/edit.html.erb
<div class="row">
  <div class="panel-header">
    <h4>Update availability</h4>
  </div>
  <%= render partial: 'form' %>
</div>

app/views/property_availabilities/index.html.erb
<div class="row">

  <div class="col-md-7">
    <h3>Available Dates </h3>
    <%= link_to "Add availability", new_property_property_availability_path(@property), class: 'btn btn-custom' %>
  <hr>
  <div class="col-md-4">
<br>
<% @property_availabilities.each do |pa| %>
  <h4><%= pa.date.strftime('%b %d, %Y') %></h4>
  <% if pa.property.owner == current_user %>
  <%= link_to "Make unavailable", edit_property_property_availability_path(@property, pa, :reserved => true), class: 'btn btn-warning' %><br><br>
  <% end %>
<% end %>
<div>

app/views/property_availabilities/new.html.erb
<div class="row">
  <div class="panel-header">
    <h4>Add availability</h4>
  </div>
  <%= render partial: 'form' %>
</div>