config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      namespace :properties do
        get 'most_guests', to: 'most_guests#index'
        get 'most_expensive', to: 'most_expensive#index'
        get 'by_state', to: 'by_state#index'
        scope ':property_id' do
          resources :reservations, only: [:create]
        end

        resources :search, only: [:index]
        resources :properties, only: [:index]
      end
      namespace :reservations do
        get '/by_month', to: 'month#index'
        get '/revenue_by_month', to: 'revenue_by_month#index'
        get '/highest_revenue_cities', to: 'cities_revenue#index'
        get '/revenue_by_state', to: 'revenue_by_state#index'
      end
      namespace :users do
        namespace :reservations do
          get '/nights', to: 'nights#index'
          get '/bookings', to: 'bookings#index'
        end
        namespace :properties do
          get '/most_properties', to: 'most_properties#index'
        end
        namespace :money do
          get '/most_spent', to: 'most_spent#index'
          get '/most_revenue', to: 'most_revenue#index'
        end
      end
    end
  end

  get '/sign_up', to: 'signup#index'
  get '/log_in', to: 'login#index'
  get '/dashboard', to: 'dashboard#index'
  delete '/logout', to: 'sessions#destroy'

  devise_for :users,
    :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"},
    :path_names => {
    	:verify_authy => "/verify-token",
    	:enable_authy => "/enable_authy",
    	:verify_authy_installation => "/verify-installation"
      }

  resources :users, only: [:edit, :update]

  namespace :admin do
    get '/dashboard', to: 'dashboard#index'
    resources :properties, only: [:index, :edit, :update]
  end

  resources :users, only: [:edit, :update, :show]

  namespace :reservations do
    scope ':reservation_id' do
      resources :property_reviews, only: [:new, :create]
      resources :user_reviews, only: [:new, :create]
    end
  end

  resources :properties,  only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :property_availabilities, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  resources :reservations, only: [:new, :update]

  namespace :user do
    resources :conversations, only: [:index, :show, :create] do
      resources :messages, only: [:create]
    end
    resources :properties, only: [:index, :show]
  end

  mount ActionCable.server => '/cable'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @featured_properties = Property.limit(4).order("RANDOM()")
  end

end

app/views/home/index.html.erb
<% content_for :top_content do %>
  <div class="jumbotron">
    <div class="container">
      <span class="title">Fairbnb</span> <span class="subtitle"> &nbsp; Book unique homes and experience a city like a local. Fairly? :)</span>
    </div>
  </div>
  <%= render partial: 'partials/search_home' %>
  <div class="container">
    <div class="all_homes">
      <h2>Homes</h2>
      <div class="card-deck">
        <% @featured_properties.each do |property| %>
        <div class="card">
          <%= image_tag property.image_url, class: "card-img-top", size: "250x250" %>
          <div class="card-block">
            <p class="card-text"> <a href="<%= property_path(property.id) %>"><%= property.name[0..28] %></a></p>
          </div>
        </div>&nbsp;&nbsp;&nbsp;&nbsp;
        <% end %>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="featured_cities">
      <h2>Featured Cities</h2>
      <div class="card-deck">
        <div class="card">

          <%= image_tag "http://www.planetware.com/photos-tiles/colorado-denver-city-view-and-mountains.jpg", class: "card-img-top", size: "250x250" %>
          <div class="card-block">
            <p class="card-text"><%= link_to "Denver","/properties?utf8=✓&city=Denver&check_in=&check_out=&guests=" %></p>
          </div>
        </div>&nbsp;&nbsp;&nbsp;&nbsp;

        <div class="card">

          <%= image_tag "http://www.myhockeytournaments.com/img/sites/chicago/001.jpg", class: "card-img-top", size: "250x250" %>
          <div class="card-block">
            <p class="card-text"><%= link_to "Chicago","/properties?utf8=✓&city=Chicago&check_in=&check_out=&guests=" %></p>
          </div>
        </div>&nbsp;&nbsp;&nbsp;&nbsp;

        <div class="card">

          <%= image_tag "http://www.visitflorida.com/content/dam/visitflorida/en-us/images/articles/2011/march/1300805920_miami_cocktail-hour-at-cafe-sambal_sm.jpg", class: "card-img-top", size: "250x250" %>
          <div class="card-block">
            <p class="card-text"><%= link_to "Miami","/properties?utf8=✓&city=Miami&check_in=&check_out=&guests=" %></p>
          </div>
        </div>&nbsp;&nbsp;&nbsp;&nbsp;

        <div class="card">

          <%= image_tag "https://farm8.staticflickr.com/7386/13883313211_587c22bdae_b.jpg", class: "card-img-top", size: "250x250" %>
          <div class="card-block">
            <p class="card-text"><%= link_to "Wauwatosa","/properties?utf8=✓&city=Wauwatosa&check_in=&check_out=&guests=" %></p>
          </div>
        </div>&nbsp;&nbsp;&nbsp;&nbsp;

      </div>
    </div>
  </div>
<% end %>