config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      namespace :properties do
        get 'most_guests', to: 'most_guests#index'
        get 'most_expensive', to: 'most_expensive#index'
        get 'by_state', to: 'by_state#index'
        scope ':property_id' do
          resources :reservations, only: [:create]
        end

        resources :search, only: [:index]
        resources :properties, only: [:index]
      end
      namespace :reservations do
        get '/by_month', to: 'month#index'
        get '/revenue_by_month', to: 'revenue_by_month#index'
        get '/highest_revenue_cities', to: 'cities_revenue#index'
        get '/revenue_by_state', to: 'revenue_by_state#index'
      end
      namespace :users do
        namespace :reservations do
          get '/nights', to: 'nights#index'
          get '/bookings', to: 'bookings#index'
        end
        namespace :properties do
          get '/most_properties', to: 'most_properties#index'
        end
        namespace :money do
          get '/most_spent', to: 'most_spent#index'
          get '/most_revenue', to: 'most_revenue#index'
        end
      end
    end
  end

  get '/sign_up', to: 'signup#index'
  get '/log_in', to: 'login#index'
  get '/dashboard', to: 'dashboard#index'
  delete '/logout', to: 'sessions#destroy'

  devise_for :users,
    :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"},
    :path_names => {
    	:verify_authy => "/verify-token",
    	:enable_authy => "/enable_authy",
    	:verify_authy_installation => "/verify-installation"
      }

  resources :users, only: [:edit, :update]

  namespace :admin do
    get '/dashboard', to: 'dashboard#index'
    resources :properties, only: [:index, :edit, :update]
  end

  resources :users, only: [:edit, :update, :show]

  namespace :reservations do
    scope ':reservation_id' do
      resources :property_reviews, only: [:new, :create]
      resources :user_reviews, only: [:new, :create]
    end
  end

  resources :properties,  only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :property_availabilities, only: [:index, :new, :create, :edit, :update, :destroy]
  end

  resources :reservations, only: [:new, :update]

  namespace :user do
    resources :conversations, only: [:index, :show, :create] do
      resources :messages, only: [:create]
    end
    resources :properties, only: [:index, :show]
  end

  mount ActionCable.server => '/cable'
end

app/models/property.rb
class Property < ApplicationRecord
  extend FairBnb::PropertyApiHelpers

  belongs_to :room_type
  belongs_to :owner, class_name: "User", foreign_key: "owner_id"

  has_many :reservations
  has_many :property_availabilities
  has_many :property_reviews

  validates :name, :number_of_guests, :number_of_beds, :number_of_rooms,
            :description, :price_per_night, :address, :city, :state, :zip,
            :image_url, :status, presence: true

  geocoded_by :geocode_address,  :latitude  => :lat, :longitude => :long
  after_validation :geocode

  enum status: %w(pending active archived)

  scope :within_zone, -> (params) { near(location_method(params[:location]), params[:location][:radius]) }
  scope :with_guests, -> (params) { where("number_of_guests >= ?", params[:guests]) }

  def self.search(params)
    return nil if params[:guests].nil? && params[:location].nil? && params[:dates].nil?
    scopes = []
    scopes << 'with_guests' if params[:guests]
    scopes << 'within_zone' if params[:location]

    scoped = chain_scopes(scopes, params)
    scoped = available(params, scoped) if params[:dates]
    scoped
  end

  def self.available(params, scoped = Property.all)
    checkin = date_range(params)[:checkin]
    checkout = date_range(params)[:checkout]

    scoped.merge(find_by_sql([
      "SELECT properties.* FROM properties
      JOIN property_availabilities ON property_availabilities.property_id = properties.id
      WHERE property_availabilities.date BETWEEN ? AND ?
      EXCEPT
      SELECT properties.* FROM properties
      INNER JOIN property_availabilities ON property_availabilities.property_id = properties.id
      WHERE property_availabilities.reserved = TRUE AND property_availabilities.date BETWEEN ? AND ?",
      checkin, checkout, checkin, checkout ]))
  end

  def self.chain_scopes(scopes, params)
    return Property.all if scopes.empty?
    scopes.inject(self) { |chain, scope| chain.send(scope, params) }
  end

  def self.location_method(params)
    if params[:lat].nil? || params[:long].nil?
      "#{params[:city]}, #{params[:state]}"
    else
      [params[:lat], params[:long]]
    end
  end

  def self.date_range(params)
    { checkin: DateTime.strptime(params[:dates].split('-')[0].strip, '%m/%d/%Y'),
      checkout: DateTime.strptime(params[:dates].split('-')[1].strip, '%m/%d/%Y') }
  end

  def prepare_address
    [address, city, state, zip].compact.join('+')
  end

  def geocode_address
    [address, city, state, zip].compact.join(', ')
  end

  def two_digit_price
    '%.2f' % price_per_night.to_f
  end

  def reviews
    property_reviews
  end

  def average_rating
    property_reviews.average(:rating).round(2)
  end

  def get_weather
    service = WeatherService.new({city: city, state: state})
    raw_weather = service.find_by_location

    if raw_weather == nil
      "Invalid city name; no weather information available."
    else
      Weather.new(raw_weather)
    end
  end

  def format_check_in_time
    DateTime.parse(check_in_time).strftime("%l:%M%P")
  end

  def format_check_out_time
    DateTime.parse(check_out_time).strftime("%l:%M%P")
  end
end

app/controllers/admin/properties_controller.rb
class Admin::PropertiesController < Admin::BaseController

  def index
    @properties = Property.all
  end

  def update
    @property = Property.find(params[:id])

    if params[:status] == "active"
      @property.update_attributes(status: :active)
      @property.save
    end
    redirect_to admin_properties_path
  end

end

app/controllers/api/v1/properties/by_state_controller.rb
class Api::V1::Properties::ByStateController < ApplicationController
  def index
    render json: StatePresenter.new(Property.by_state)
  end
end

app/controllers/api/v1/properties/most_expensive_controller.rb
class Api::V1::Properties::MostExpensiveController < ApplicationController

  def index
    render json: Property.most_expensive(search_params)
  end

  private

    def search_params
      params.permit(:city, :limit)
    end

end

app/controllers/api/v1/properties/most_guests_controller.rb
class Api::V1::Properties::MostGuestsController < ApplicationController

  def index
    render json: Property.most_guests(search_params)
  end

  private

    def search_params
      params.permit(:city, :limit)
    end

end

app/controllers/api/v1/properties/properties_controller.rb
class Api::V1::Properties::PropertiesController < ApplicationController
  def index
    @presenter = PropertyPresenter.new(params)
    @presenter.set_attributes
    if @presenter.properties.empty?
      render json: {status: 400}
    end
  end
end

app/controllers/api/v1/properties/reservations_controller.rb
class Api::V1::Properties::ReservationsController < ApiController

  before_action :get_property, only: :create

  def create
    reservation = @property.reservations.new(reservation_params)
    if reservation.save
      Conversation.create_trip_conversation(params)
      render json: {success:"Reservation Created", reservation: reservation}, status: 201
    else
      render json: {error: "Missing Parameters"}, status: 401
    end
  end

  private

    def reservation_params
      params.require(:reservation).permit(
        :start_date,
        :end_date,
        :number_of_guests,
        :renter_id
      )
    end

    def get_property
      @property = Property.find(params[:property_id])
    end
end

app/controllers/api/v1/properties/search_controller.rb
class Api::V1::Properties::SearchController < ApiController

  def index
    render json: Property.search(params), status: 200
  end

end

app/controllers/api/v1/users/money/most_revenue_controller.rb
class Api::V1::Users::Money::MostRevenueController < ApplicationController

  def index
    if params[:limit]
      render json: User.most_revenue(params[:limit])
    else
      render json: User.most_revenue
    end
  end
end

app/controllers/api/v1/users/money/most_spent_controller.rb
class Api::V1::Users::Money::MostSpentController < ApplicationController

  def index
    render json: User.most_money_spent(params[:limit])
  end
end

app/controllers/api/v1/users/properties/most_properties_controller.rb
class Api::V1::Users::Properties::MostPropertiesController < ApplicationController

  def index
    if params[:limit]
      render json: User.most_properties(params[:limit])
    else
      render json: User.most_properties
    end
  end
end

app/controllers/api/v1/users/reservations/bookings_controller.rb
class Api::V1::Users::Reservations::BookingsController < ApplicationController

  def index
    if params[:limit]
      render json: User.reservations_by_bookings(params[:limit])
    else
      render json: User.reservations_by_bookings
    end
  end

end

app/controllers/api/v1/users/reservations/nights_controller.rb
class Api::V1::Users::Reservations::NightsController < ApplicationController

  def index
    if params[:limit]
      render json: User.reservations_by_night(params[:limit])
    else
      render json: User.reservations_by_night
    end
  end

end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController

  def show
    @property = Property.find(params[:id])
    @weather = @property.get_weather
  end

  def index
  end

  def new
    @room_types = RoomType.all
    @property = Property.new
  end

  def create
    @property = current_user.properties.new(properties_params)
    @room_types = RoomType.all
    if @property.save
      flash[:success] = "Your rental property has been submitted for approval. You will be contacted as soon as your property is approved!"
      redirect_to new_property_property_availability_path(@property)
    else
      flash[:danger] = "Sorry! Something went wrong. Please try again."
      render :new
    end
  end

  def edit
    @room_types = RoomType.all
    @property = current_user.properties.find(params[:id])
  end

  def update
    @property = current_user.properties.find(params[:id])
    @property.update(properties_params)
    if @property.save
      flash[:success] = "Your edits have beeen submitted for approval. You will receive a notice when property is updated."
      redirect_to property_path(@property)
    else
      redirect_to edit_property_path(@property)
    end
  end

  private

    def properties_params
    params.require(:property).permit(:name, :number_of_guests, :number_of_beds, :number_of_rooms,
                                     :number_of_bathrooms, :description, :price_per_night, :address,
                                     :city, :state, :zip, :image_url, :room_type_id ,:check_in, :guests,
                                     :check_in_time, :check_out_time)
    end
end

app/controllers/user/conversations_controller.rb
class User::ConversationsController < ApplicationController
  before_action :set_conversation, only: [:show]
  before_action :check_participating!, only: [:show]

  def index
    @conversations = Conversation.participating(current_user)
  end

  def show
  end

  def create
    conversation = Conversation.message_host(current_user, params)
    redirect_to user_conversation_path(conversation)
  end

  private
    def conversation_params
      params.require(:conversation).permit(:title)
    end

    def set_conversation
      @conversation = Conversation.participating(current_user).find(params[:id])
    end

    def check_participating!
      redirect_to root_path unless @conversation && @conversation.participates?(current_user)
    end
end

app/controllers/user/messages_controller.rb
class User::MessagesController < ApplicationController
  before_action :set_conversation

  def create
    message = @conversation.messages.build(message_params)
    message.user_id = current_user.id
    if message.save
      ActionCable.server.broadcast "conversation_channel_#{params[:conversation_id]}",
                                   content:  message.content,
                                   first_name: message.user.first_name,
                                   timestamp: message.timestamp
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end

  def set_conversation
    @conversation = Conversation.find_by(id: params[:conversation_id])
    redirect_to(root_path) and return unless @conversation && @conversation.participates?(current_user)
  end
end

app/controllers/user/properties_controller.rb
class User::PropertiesController < ApplicationController
  def index
    @properties = current_user.properties
  end

  def show
    @property = Property.find(params[:id])
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
      if @user.phone_number.nil?
        redirect_to edit_user_path(@user)
      else
        redirect_to dashboard_path
      end
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to root_path
    end
  end

  def google_oauth2
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in @user, :event => :authentication
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
      if @user.phone_number.nil?
        redirect_to edit_user_path(@user)
      else
        redirect_to dashboard_path
      end
    else
      session["devise.google_data"] = request.env["omniauth.auth"].except(:extra)
      redirect_to dashboard_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: :show

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to dashboard_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :image_url, :phone_number, :description, :hometown)
  end

end

app/views/user/properties/index.html.erb
<h1>My Properties</h1>
<% @properties.each do |property| %>
  <div class="panel panel-default" id="property-<%= property.id %>">
    <div class="panel-heading">
      <h3 class="panel-title"><%= link_to property.name, user_property_path(property.id) %></h3>
    </div>
    <div class="panel-body">
      <div class="col-md-6">
        <p>Status: <%= property.status %></p>
        <p>Price per Night: <%= number_to_currency(property.price_per_night) %></p>
        <p>Number of:</p>
        <ul>
          <li>Guests: <%= property.number_of_guests %></li>
          <li>Beds: <%= property.number_of_beds %></li>
          <li>Rooms: <%= property.number_of_rooms %></li>
          <li>Bathrooms: <%= property.number_of_bathrooms %></li>
        </ul>
      </div>
      <div class="col-md-6">
        <h3>Location:</h3>
        <p><%= property.address %></p>
        <p><%= property.city %>, <%= property.state %> <%= property.zip %></p>
      </div>
      <div class="col-md-12">
        <hr/>
        <h4>Total Reservation Requests: <%= property.reservations.count %></h4>
        <ul class="nav nav-pills" role="tablist">
          <% if property.reservations.in_progress.count > 0 %>
            <li role="presentation" class="active">
              <%= link_to user_property_path(property.id) do %>
                In Progress <span class='badge'><%= property.reservations.in_progress.count %></span>
              <% end %>
            </li>
          <% end %>
          <% if property.reservations.pending.count > 0 %>
            <li role="presentation" class="active">
              <%= link_to user_property_path(property.id) do %>
                Pending <span class="badge"><%= property.reservations.pending.count %></span>
              <% end %>
            </li>
          <% end %>
          <li role="presentation" >
            <%= link_to user_property_path(property.id) do %>
              Confirmed <span class="badge"><%= property.reservations.confirmed.count %></span>
            <% end %>
          </li>
          <li role="presentation" >
            <%= link_to user_property_path(property.id) do %>
              Past <span class="badge"><%= property.reservations.finished.count %></span>
            <% end %>
          </li>
          <li role="presentation" >
            <%= link_to user_property_path(property.id) do %>
              Declined <span class="badge"><%= property.reservations.declined.count %></span>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>
<% end %>

app/views/user/properties/show.html.erb
<h1><%= @property.name %></h1>

<div class="panel panel-default">
  <div class="panel-body">
    <div class="col-md-6">
      <p>Status: <%= @property.status %></p>
      <p>Price per Night: <%= number_to_currency(@property.price_per_night) %></p>
      <p>Number of:</p>
      <ul>
        <li>Guests: <%= @property.number_of_guests %></li>
        <li>Beds: <%= @property.number_of_beds %></li>
        <li>Rooms: <%= @property.number_of_rooms %></li>
        <li>Bathrooms: <%= @property.number_of_bathrooms %></li>
      </ul>
    </div>
    <div class="col-md-6">
      <h3>Location:</h3>
      <p><%= @property.address %></p>
      <p><%= @property.city %>, <%= @property.state %> <%= @property.zip %></p>
    </div>
  </div>
</div>
<% if @property.reservations.in_progress.count > 0 %>
  <div class="well well-lg" id="in-progress-requests">
    <%= render partial: 'reservations/requests', locals: {status: 'in_progress', property: @property} %>
  </div>
<% end %>
<% if @property.reservations.pending.count > 0 %>
  <div class="panel panel-default" id="pending-requests">
    <div class="panel-heading">
      <h3 class="panel-title">Pending Requests</h3>
    </div>
    <div class="panel-body">
      <%= render partial: 'reservations/requests', locals: {status: 'pending', property: @property} %>
    </div>
  </div>
<% end %>
<div class="panel panel-default" id="confirmed-requests">
  <div class="panel-heading">
    <h3 class="panel-title">Confirmed Requests</h3>
  </div>
  <div class="panel-body">
    <% if @property.reservations.confirmed.count > 0 %>
      <%= render partial: 'reservations/requests', locals: {status: 'confirmed', property: @property} %>
    <% else %>
      <p>No Confirmed Requests</p>
    <% end %>
  </div>
</div>
<div class="panel panel-default" id="finished-requests">
  <div class="panel-heading">
    <h3 class="panel-title">Finished Requests</h3>
  </div>
  <div class="panel-body">
    <% if @property.reservations.finished.count > 0 %>
      <%= render partial: 'reservations/requests', locals: {status: 'finished', property: @property} %>
    <% else %>
      <p>No Finished Requests</p>
    <% end %>
  </div>
</div>
<div class="panel panel-default" id="declined-requests">
  <div class="panel-heading">
    <h3 class="panel-title">Declined Requests</h3>
  </div>
  <div class="panel-body">
    <% if @property.reservations.declined.count > 0 %>
      <%= render partial: 'reservations/requests', locals: {status: 'declined', property: @property} %>
    <% else %>
      <p>No Declined Requests</p>
    <% end %>
  </div>
</div>